# See http://www.appveyor.com/docs/appveyor-yml for many more options
image: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /Update README.md/

install:
  - ps: Install-PackageProvider Nuget -Force -Verbose
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -Force -Verbose
  - ps: Install-Module -Name Pester -Force -Verbose
  - ps: Install-Module -Name PSScriptAnalyzer -Force -Verbose

build: false

test_script:
# Test with native PS version
  - ps: Invoke-ScriptAnalyzer -Path .\PS7Zip -Verbose
  - ps: . .\appveyor.tests.ps1 -Test
# Finalize pass - collect and upload results
  - ps: . .\appveyor.tests.ps1 -Finalize
