# See http://www.appveyor.com/docs/appveyor-yml for many more options
image: WMF 5

environment:
  NuGetApiKey:
    secure: SzN/9XuDneoXfDr9MaS6Ugt1Bsj4MqxzcKB45uvBRGrmSozL+83cEfNEYdd/SYc2

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /.(md|yml)/

install:
  - ps: Install-PackageProvider Nuget -Force | Out-Null
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module -Name Pester -Force
  - ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
# Test with native PS version
  - ps: . .\appveyor.ps1 -Test

# Finalize pass - collect and upload results
  - ps: . .\appveyor.ps1 -Finalize

deploy_script:
  - ps: . .\appveyor.ps1 -Deploy
