version: '1.3.{build}.0'
image: WMF 5
skip_commits:
  message: /updated readme.*|update readme.*s/
build: off

environment:
  NuGetApiKey:
    secure: SzN/9XuDneoXfDr9MaS6Ugt1Bsj4MqxzcKB45uvBRGrmSozL+83cEfNEYdd/SYc2

test_script:
  - ps: ./build.ps1
