# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: '1.3.{build}.0'

os:
  - "WMF 5"

environment:
  NuGetApiKey:
    secure: SzN/9XuDneoXfDr9MaS6Ugt1Bsj4MqxzcKB45uvBRGrmSozL+83cEfNEYdd/SYc2

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /.(md|yml)/

install:
  - ps: . .\appveyor.ps1 -Install

test_script:
# Test with native PS version
  - ps: . .\appveyor.ps1 -Test
  - ps: powershell.exe -Version 2 -File .\appveyor.ps1 -Install -Test

after_test:
# Build pass - make markdown docs
  - ps: . .\appveyor.ps1 -Build

deploy_script:
  - ps: If ($PSVersionTable.PSVersion.Major -ge 5) {. .\appveyor.ps1 -Deploy}

on_finish:
# Finalize pass - collect and upload results
  - ps: . .\appveyor.ps1 -Finalize
